IBH/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("main.urls")),
    path("administrator/", include("administrator.urls", namespace='administrator')),
    path("operations_team_leader/", include("operations_team_leader.urls", namespace='operations_team_leader')),
    path("sales_manager/", include("sales_manager.urls", namespace='sales_manager')),
    path("sales_team_leader/", include("sales_team_leader.urls", namespace='sales_team_leader')),
    path("operations_manager/", include("operations_manager.urls", namespace='operations_manager')),
    path("api/", include("api.urls", namespace='api')),
    path("leads/", include("leads.urls", namespace="leads")),
    path("sales/", include("sales.urls", namespace="sales")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    # import debug_toolbar  # Import Debug Toolbar only in DEBUG mode
    # urlpatterns += [
    #     path("__debug__/", include(debug_toolbar.urls)),  # Add Debug Toolbar URLs
    # ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

leads/urls.py
from django.urls import path
from .views import index, auto_fill, notifications, notification_detail, sheet_detail, upload_sheet, download_auto_fill_result
from main.views import leads_average_view
from django.conf import settings
from django.conf.urls.static import static

app_name="leads"

urlpatterns = [
    path('', index, name='leads_index'),
    path('auto-fill/', auto_fill, name='auto-fill'),
    path('upload-sheet/', upload_sheet, name='upload-sheet'),
    path('leads-average/', leads_average_view, name='leads-average'),
    # path('import-sheets/', import_lead_termination_history, name='import-sheets'),
    path('notifications/', notifications, name='notifications'),
    path('notifications/<int:notification_id>/', notification_detail, name='leads-notification-detail'),
    path('notifications/<int:notification_id>/sheet/<int:sheet_id>/', sheet_detail, name='leads-sheet-detail'),
    path('notifications/<int:notification_id>/download-auto-fill-result/', download_auto_fill_result, name='download-auto-fill-result'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .views import index, login_view, logout_view, sheet_list, log_inactivity

app_name="main"

urlpatterns = [
    path("", index, name="index"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path('api/sheets/', sheet_list, name='sheet-list'),
    path('log-inactivity/', log_inactivity, name='log_inactivity'),
]

templates/layout/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta content="width=device-width, initial-scale=1.0" name="viewport" />

  <title>The Genie</title>
  <link rel="icon" href="{% static 'assets/Genie_logo.jpeg' %}" type="image/x-icon">
  <meta content="" name="description" />
  <meta content="" name="keywords" />

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect" />
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet" />

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet" />
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet" />
  <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet" />
  <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet" />
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet" />
  <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet" />

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />

  <!-- PopUp Notification Library -->
  <link href="{% static 'assets/css/notification.css' %}" rel="stylesheet" />
  <script src="{% static 'assets/js/notification.js' %}"></script>
  <script src="{% static 'assets/js/jquery.js' %}"></script>

</head>

<body>

  {% include "layout/header.html" %}
  {% include 'layout/sidebar.html' %}
  <main id="main" class="main">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% block content %} {% endblock %}
  </main>
</body>
<script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/chart.js/chart.umd.js' %}"></script>
<script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
<script src="{% static 'assets/vendor/quill/quill.js' %}"></script>
<script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
<script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
<script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'assets/js/main.js' %}"></script>

<script>

(function () {
  let timeout; // Use `let` to prevent global variable issues

  function resetTimeout() {
    clearTimeout(timeout);
    // Set a timeout to log inactivity after 5 minutes (300000 milliseconds)
    timeout = setTimeout(logInactivity, 300000); // Adjusted to 5 minutes
  }

  function logInactivity() {
    console.log("Logging user inactivity...");

    fetch("{% url 'main:log_inactivity' %}", {
      method: "POST",
      headers: {
        "X-CSRFToken": "{{ csrf_token }}",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        message: "User inactive for 5 minutes",
      }),
    })
      .then((response) => {
        if (response.ok) {
          console.log("Inactivity logged successfully.");
        } else {
          console.error("Logging inactivity failed:", response);
        }
      })
      .catch((error) => console.error("Error logging inactivity:", error));
  }

  // Reset the inactivity timeout whenever there is mouse movement
  document.addEventListener("mousemove", resetTimeout);

  // Start the inactivity timer
  resetTimeout();
})();

</script>


</html>

templates/layout/clear_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta content="width=device-width, initial-scale=1.0" name="viewport" />

  <title>Genie</title>
  <link rel="icon" href="{% static 'assets/Genie_logo.jpeg' %}" type="image/x-icon">
  <meta content="" name="description" />
  <meta content="" name="keywords" />

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect" />
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet" />

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet" />
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet" />
  <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet" />
  <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet" />
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet" />
  <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet" />

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />
</head>

<body>
  {% block content%} {%endblock%}
</body>
<script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/chart.js/chart.umd.js' %}"></script>
<script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
<script src="{% static 'assets/vendor/quill/quill.js' %}"></script>
<script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
<script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
<script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'assets/js/main.js' %}"></script>

</html>

templates/layout/header.html
{% load static %}

<style>
  .nav-bar-counter {
    position: relative;
  }

  .badge {
    font-size: 0.75rem;
    padding: 5px;
  }
</style>

<header id="header" class="header fixed-top d-flex align-items-center">
  <div class="d-flex align-items-center justify-content-between">
    <a href="/" class="logo d-flex align-items-center">
      <img src="{% static 'assets/Genie_logo.jpeg' %}" alt="" />
      <span class="d-none d-lg-block">The Genie</span>
    </a>
    <i class="bi bi-list toggle-sidebar-btn"></i>
  </div>
  <!-- End Logo -->

  <nav class="header-nav ms-auto">
    <ul class="d-flex align-items-center">
      <li class="nav-item d-block d-lg-none">
        <a class="nav-link nav-icon search-bar-toggle" href="#">
          <i class="bi bi-search"></i>
        </a>
      </li>
      <!-- End Search Icon-->

      <li class="nav-item dropdown">
        {% if request.user.is_authenticated %}
        {% with request.user.groups.first as user_group %}
        {% if user_group %}
        {% if user_group.name == 'operations_team_leader' %}
        <a class="nav-link nav-icon nav-bar-counter" href="{% url 'operations_team_leader:notifications' %}">
        {% elif user_group.name == 'operations_manager' %}
        <a class="nav-link nav-icon nav-bar-counter" href="{% url 'operations_manager:notifications' %}">
        {% elif user_group.name == 'leads' %}
        <a class="nav-link nav-icon nav-bar-counter" href="{% url 'leads:notifications' %}">
        {% elif user_group.name == 'sales_manager' %}
        <a class="nav-link nav-icon nav-bar-counter" href="{% url 'sales_manager:notifications' %}">
        {% elif user_group.name == 'sales_team_leader' %}
        <a class="nav-link nav-icon nav-bar-counter" href="{% url 'sales_team_leader:notifications' %}">
        {% elif user_group.name == 'sales' %}
        <a class="nav-link nav-icon nav-bar-counter" href="{% url 'sales:notifications' %}">
        {% endif %}
        {% endif %}
        {% endwith %}
        {% endif %}

          <i class="bi bi-bell"></i>
          {% if unread_notifications_count > 0 %}
          <span class="badge notification-badge bg-primary badge-number">{{ unread_notifications_count }}</span>
          {% else %}
              <span class="badge notification-badge bg-primary badge-number" style="display: none;"></span>
          {% endif %}
      </li>
      <!-- End Notification Nav -->


      <li class="nav-item dropdown pe-3">
        <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">

          <span class="d-none d-md-block dropdown-toggle px-2"
            style="font-size: 1.2rem">{{request.user.username}}</span> </a>
        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
          <li class="dropdown-header">
            <h6>{{request.user.username}}</h6>
            <span>{{request.user.groups.first.name}}</span>
          </li>
          <li>
            <hr class="dropdown-divider" />
          </li>

          <li>
            <a class="dropdown-item d-flex align-items-center" href="{% url 'main:logout' %}">
              <i class="bi bi-box-arrow-right"></i>
              <span>Sign Out</span>
            </a>
          </li>
        </ul>
        <!-- End Profile Dropdown Items -->
      </li>
      <!-- End Profile Nav -->
    </ul>
  </nav>
  <!-- End Icons Navigation -->
</header>

<!-- <script>
  const notificationSocket = new WebSocket(
    'ws://' + window.location.host + '/ws/notifications/'
  );

  document.addEventListener('DOMContentLoaded', function () {
    loadNotifications();
  });

  function loadNotifications() {
    const notifications = JSON.parse(localStorage.getItem('notifications')) || [];

    // Filter unread notifications
    const unreadNotifications = notifications.filter(notification => !notification.read);

    const notificationBadge = document.querySelector('.badge-number');
    unreadNotificationsCount = unreadNotifications.length;
    if (unreadNotificationsCount > 0) {
      notificationBadge.textContent = unreadNotificationsCount;
      notificationBadge.style.display = 'inline';
    }
  }

  notificationSocket.onmessage = function (e) {
    const data = JSON.parse(e.data);
    const message = data['message'];
    const id = data['id'];
    const read = data['read'];
    const state = data['state'];

    // Save and display new notification
    const newNotification = {
      id: id,
      title: 'New Notification',
      message: message,
      timestamp: new Date().toLocaleTimeString(),
      read: read
    };

    saveNotification(newNotification);

    const popup = Notification({
      position: 'top-right',
      duration: 5000,
      isHidePrev: false,
      isHideTitle: false,
      maxOpened: 3,
    });

    if (state == 'SUCCESS') {
      // success
      popup.success({
        title: newNotification.title,
        message: newNotification.message
      });
    } else if (state == 'INFO') {
      // info
      popup.info({
        title: newNotification.title,
        message: newNotification.message
      })
    } else if (state == 'WARNING') {
      // warning
      popup.warning({
        title: newNotification.title,
        message: newNotification.message
      })
    } else if (state == 'ERROR') {
      // error
      popup.error({
        title: newNotification.title,
        message: newNotification.message
      })
    }

    loadNotifications();
  };

  function saveNotification(notification) {
    const notifications = JSON.parse(localStorage.getItem('notifications')) || [];
    const unreadNotifications = notifications.filter(notification => !notification.read);

    // Update the existing notification if it already exists
    const existingIndex = unreadNotifications.findIndex(n => n.id === notification.id);
    if (existingIndex > -1) {
      unreadNotifications[existingIndex] = notification;
    } else {
      unreadNotifications.push(notification);
    }

    localStorage.setItem('notifications', JSON.stringify(unreadNotifications));
  }

  notificationSocket.onclose = function (e) {
    console.error('Notification socket closed unexpectedly');
  };

  document.querySelector('.nav-bar-counter').addEventListener('click', function (e) {
    localStorage.removeItem('notifications');
  })
</script> -->